line-length = 88
include = [
    "src/**/*.py",
    "tests/**/*.py"
]

[format]
quote-style = "double"
skip-magic-trailing-comma = true

[lint]
extend-select = ["B", "D", "E", "F", "I", "Q", "RUF022", "S", "TC", "W505"]
ignore = ["D100", "D101", "D102", "D103", "D104", "D105", "D106", "D107"]

[lint.per-file-ignores]
# Ignore S101 (use of assert) in test files
"tests/**/*.py" = ["S101"]

[lint.pycodestyle]
max-doc-length = 79
max-line-length = 88

[lint.pydocstyle]
convention = "numpy"

[lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "double"
multiline-quotes = "double"

[lint.flake8-type-checking]
runtime-evaluated-base-classes = ["pydantic.BaseModel", "sqlmodel.SQLModel"]
runtime-evaluated-decorators = ["pydantic.validate_call", "pydantic.dataclasses.dataclass"]
quote-annotations = false

[lint.isort]
split-on-trailing-comma = false
